<?php

use App\Models\Image;
use App\Models\Product;
use App\Models\Variant;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (Product::count() == 0) {
            $products = [
                // local roasters
                [
                    'product_name' => 'Santa Lucia',
                    'description' => 'Tons of chocolaty sweetness cools nicely to a gentle fruity finish.',
                    'varietal' => 'Acaia',
                    'altitude' => '1150m',
                    'sku' => strtolower(str_replace(" ", "-", 'Santa Lucia')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Milk Chocolate, Caramel, Hazelnut with Orange Acidity',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '1',
                    'brand_id' => '1',
                    'brand_type_id' => '1',
                    'characteristic_id' => '1',
                    'best_for_id' => '6',
                    'level_id' => '3',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Santa Lucia')) . ' - 250g',
                            'price' => '45',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '8',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'Santa Lucia')) . ' - 500g',
                            'price' => '90',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Bond Street',
                    'description' => 'Full-bodied and easy-drinking, this coffee\'s notes of milk chocolate work in harmony with a strawberry and hazelnut sweetness to make a cup of coffee that anyone can enjoy.',
                    'varietal' => null,
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Bond Street')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Milk Chocolate, Hazelnut & Strawberry',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '1',
                    'brand_id' => '1',
                    'brand_type_id' => '1',
                    'characteristic_id' => '1',
                    'best_for_id' => '6',
                    'level_id' => '3',
                    'process_id' => null,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Bond Street')) . ' - 250g',
                            'price' => '45',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'Bond Street')) . ' - 500g',
                            'price' => '90',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Colombia Washed',
                    'description' => 'Rich, robust, and nostalgic: this full-bodied cup\'s hints of buttercream and cocoa invoke an old-world romance.',
                    'varietal' => null,
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Colombia Washed')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Buttercream, Cocoa Nibs, Brown Sugar',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '2',
                    'brand_type_id' => '1',
                    'characteristic_id' => '7',
                    'best_for_id' => '9',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 2,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => null,
                            'title' => '5 sachets',
                            'sku' => strtolower(str_replace(" ", "-", 'Colombia Washed')) . ' - 5 sachets',
                            'price' => '75',
                            'quantity' => '100',
                            'grind_ids' => '9',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Rwanda Natural',
                    'description' => 'Tea-like and lemongrass are the notes we treasure in washed Rwandan coffees, and this lovely one combines them with a bonus blueberry sweetness.',
                    'varietal' => null,
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Rwanda Natural')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Orange, Lemongrass, Blueberries',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '3',
                    'brand_id' => '2',
                    'brand_type_id' => '1',
                    'characteristic_id' => '6',
                    'best_for_id' => '9',
                    'level_id' => '1',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 2,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => null,
                            'title' => '5 sachets',
                            'sku' => strtolower(str_replace(" ", "-", 'Rwanda Natural')) . ' - 5 sachets',
                            'price' => '75',
                            'quantity' => '100',
                            'grind_ids' => '9',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Drip Bag Sidamo',
                    'description' => 'Interested in fruity coffees, but don\'t know where to start? Here\'s your gateway: gentle apricot sweetness and a soft lemon acidity make this cup equal parts approachable and exciting.',
                    'varietal' => 'Heirloom',
                    'altitude' => '1950m',
                    'sku' => strtolower(str_replace(" ", "-", 'Drip Bag Sidamo')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Floral, Lemon Citrusy, Apricot & Chocolate',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '4',
                    'brand_id' => '3',
                    'brand_type_id' => '1',
                    'characteristic_id' => '8',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '2',
                            'reward_point' => '1',
                            'title' => '100g',
                            'sku' => strtolower(str_replace(" ", "-", 'Drip Bag Sidamo')) . ' - 100g',
                            'price' => '140',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'The Blend',
                    'description' => 'Earthy depth meets a juicy berry sweetness in a rich, chocolaty body - this blend is ready to be the wind beneath your wings.',
                    'varietal' => 'Varied',
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'The Blend')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Roasted Caramel & Chocolate ',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '5',
                    'brand_id' => '3',
                    'brand_type_id' => '1',
                    'characteristic_id' => '1',
                    'best_for_id' => '2',
                    'level_id' => '4',
                    'process_id' => 10,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'The Blend')) . ' - 250g',
                            'price' => '40',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Nyeri',
                    'description' => 'This tropical fruit bomb develops its flavor through two different, very precisely controlled fermentations, but you could be forgiven for ignoring the process and focusing on the intensely sweet results.',
                    'varietal' => 'SL28, SL34 & RUIRU 11',
                    'altitude' => '1800m',
                    'sku' => strtolower(str_replace(" ", "-", 'Nyeri')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Apricot, Green Tea, Kiwi & Cola',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '6',
                    'brand_id' => '4',
                    'brand_type_id' => '1',
                    'characteristic_id' => '3',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Nyeri')) . ' - 200g',
                            'price' => '74',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'La Cordillera',
                    'description' => 'Surprisingly delicate for a coffee hailing from Colombia, but we\'re super into it. Lovely florals meet a chocolate sweetness, making for a cup that\'s downright pretty.',
                    'varietal' => 'Castillo',
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'La Cordillera')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Chocolate & Roses',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '4',
                    'brand_type_id' => '1',
                    'characteristic_id' => '1',
                    'best_for_id' => '10',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '8',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'La Cordillera')) . ' - 500g',
                            'price' => '100',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Businde',
                    'description' => 'Burundi Naturals are a perennial favourite at Nightjar, with this plummy and juicy crop more than justifying the reputation.',
                    'varietal' => 'Red Bourbon',
                    'altitude' => '1450-1600m',
                    'sku' => strtolower(str_replace(" ", "-", 'Businde')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Blueberry, Nectarine & Malt Biscuit',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '7',
                    'brand_id' => '5',
                    'brand_type_id' => '1',
                    'characteristic_id' => '8',
                    'best_for_id' => '10',
                    'level_id' => '5',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Businde')) . ' - 250g',
                            'price' => '45',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Businde')) . ' - 1Kg',
                            'price' => '170',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Chachoeira',
                    'description' => 'This one reminds us of butterschotch, chocolate, and pear. With all that inside this full and velvety coffee, what\'s not to love?',
                    'varietal' => 'Yellow Catuai',
                    'altitude' => '1100m',
                    'sku' => strtolower(str_replace(" ", "-", 'Chachoeira')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Milk Chocolate, Butterscotch, Sapodilla Fruit',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '1',
                    'brand_id' => '5',
                    'brand_type_id' => '1',
                    'characteristic_id' => '7',
                    'best_for_id' => '1',
                    'level_id' => '1',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Chachoeira')) . ' - 250g',
                            'price' => '55',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'La Loma Estate',
                    'description' => 'Subtle & Delicate Proof that you can roast light and still develop a ton of caramelized sugar flavors, these big Caturra variety beans taste to us like milk chocolate, honey & orange, elevated by gently floral aromatics.',
                    'varietal' => 'Caturra',
                    'altitude' => '1800m',
                    'sku' => strtolower(str_replace(" ", "-", 'La Loma Estate')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Orange, Rose, Honey, Spices',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '6',
                    'brand_type_id' => '1',
                    'characteristic_id' => '6',
                    'best_for_id' => '10',
                    'level_id' => '5',
                    'process_id' => 4,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'La Loma Estate')) . ' - 250g',
                            'price' => '60',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Black Velvet Blend',
                    'description' => 'Sweet, smooth, and easy as pie: this friendly cup brings a spicy feel to its caramel sweetness and dark chocolaty body.',
                    'varietal' => 'Yellow Catuai, Cattura, Colombia, Castillo, Sumatra Typica',
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Black Velvet Blend')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Caramel, Molasses, Dark Chocolate & Spices',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '1',
                    'brand_id' => '7',
                    'brand_type_id' => '1',
                    'characteristic_id' => '7',
                    'best_for_id' => '11',
                    'level_id' => '4',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '8',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'Black Velvet Blend')) . ' - 500g',
                            'price' => '98',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Black Velvet Blend')) . ' - 1Kg',
                            'price' => '196',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Ethiopia Jasper',
                    'description' => 'How about starting your day with sugared berries and sunshine? This Ethiopian summer stunner delivers lush berry sweetness in a rich, smooth body.',
                    'varietal' => 'Guji Regional',
                    'altitude' => '1800m',
                    'sku' => strtolower(str_replace(" ", "-", 'Ethiopia Jasper')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Tropical Fruits, Purple Fruits, Floral',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '4',
                    'brand_id' => '7',
                    'brand_type_id' => '1',
                    'characteristic_id' => '3',
                    'best_for_id' => '1',
                    'level_id' => '7',
                    'process_id' => 12,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Ethiopia Jasper')) . ' - 200g',
                            'price' => '230',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Finca Las Canoas',
                    'description' => 'Bright, fruity notes are fully on display in this syrupy-bodied beauty - what a tremendously fun cup.',
                    'varietal' => 'Colombia',
                    'altitude' => '1700-1800m',
                    'sku' => strtolower(str_replace(" ", "-", 'Finca Las Canoas')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Plum, Grape Jelly, Cola',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '8',
                    'brand_type_id' => '1',
                    'characteristic_id' => '2',
                    'best_for_id' => '6',
                    'level_id' => '3',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Finca Las Canoas')) . ' - 250g',
                            'price' => '80',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Finca Las Canoas')) . ' - 1Kg',
                            'price' => '240',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Segura Venecia',
                    'description' => 'Interested in fruity coffees, but don\'t know where to start? Here\'s your gateway: gentle magnolia sweetness and a soft lemon acidity make this cup equal parts approachable and exciting.',
                    'varietal' => 'Venecia',
                    'altitude' => '1600m',
                    'sku' => strtolower(str_replace(" ", "-", 'Segura Venecia')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Magnolia, Brown Sugar, Stone Fruit',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '8',
                    'brand_id' => '8',
                    'brand_type_id' => '1',
                    'characteristic_id' => '6',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Segura Venecia')) . ' - 250g',
                            'price' => '90',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Segura Venecia')) . ' - 1Kg',
                            'price' => '230',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Guji Shakiso',
                    'description' => 'We\'re keen on this peachy, floral Ethiopian - plenty of sweetness and a surprisingly full body make for a satisfying cup indeed.',
                    'varietal' => 'Heirloom',
                    'altitude' => '1500-200m',
                    'sku' => strtolower(str_replace(" ", "-", 'Guji Shakiso')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Jasmine, Green Apple',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '4',
                    'brand_id' => '9',
                    'brand_type_id' => '1',
                    'characteristic_id' => '3',
                    'best_for_id' => '1',
                    'level_id' => '2',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Guji Shakiso')) . ' - 250g',
                            'price' => '45',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Guji Shakiso')) . ' - 1kg',
                            'price' => '175',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Ideal Estate Kiambu',
                    'description' => 'Wild, and wildly sweet: this fascinating cup brings plenty of brown sugar sweetness, and features an intriguingly delicious note of red plum.',
                    'varietal' => 'SL28, SlL34',
                    'altitude' => '1600-1700m',
                    'sku' => strtolower(str_replace(" ", "-", 'Ideal Estate Kiambu')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Red Plum, Pomegranate, Brown Sugar',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '6',
                    'brand_id' => '10',
                    'brand_type_id' => '1',
                    'characteristic_id' => '4',
                    'best_for_id' => '3',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => 'Ideal Estate Kiambu - 250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Ideal Estate Kiambu')) . ' - 250g',
                            'price' => '89',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Yenni Ramos',
                    'description' => 'Soft and silky, and just oh-so-pleasant, this clean cup offers a floral profile with just a drop of lemon acidity.',
                    'varietal' => 'Colombia',
                    'altitude' => '1900m',
                    'sku' => strtolower(str_replace(" ", "-", 'Yenni Ramos')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Grapes, Floral, Lemon, Syrup',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '2',
                    'brand_id' => '11',
                    'brand_type_id' => '1',
                    'characteristic_id' => '6',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Yenni Ramos')) . ' - 250g',
                            'price' => '40',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Signature Blend',
                    'description' => 'A super sweet, seasonal acid trip, with notes of over-ripe marmalade, roasted marshmallow, gummy bears and jammy starfruit. Pipe-dreams are made of this stuff.',
                    'varietal' => null,
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Signature Blend')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Sweet, Jam, Honey',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 1,
                    'origin_id' => '1',
                    'brand_id' => '5',
                    'brand_type_id' => '1',
                    'characteristic_id' => '9',
                    'best_for_id' => '2',
                    'level_id' => '4',
                    'process_id' => 4,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Signature Blend')) . ' - 250g',
                            'price' => '40',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Signature Blend')) . ' - 1Kg',
                            'price' => '155',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Migoti',
                    'description' => 'Big and bold, this rich coffee offers plenty of dark sweetness: think toffee or cherry. Perfect on its own, or with a splash of your milk of choice.',
                    'varietal' => 'Bourbon',
                    'altitude' => '1600-1900m',
                    'sku' => strtolower(str_replace(" ", "-", 'Migoti')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Dark Chocolate, Toffee, Cherry, Peach',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '7',
                    'brand_id' => '12',
                    'brand_type_id' => '1',
                    'characteristic_id' => '5',
                    'best_for_id' => '2',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Migoti')) . ' - 250g',
                            'price' => '40',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '8',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'Migoti')) . ' - 500g',
                            'price' => '75',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Migoti')) . ' - 1Kg',
                            'price' => '135',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Finca Julia',
                    'description' => 'Densely sweet and chocolaty, this rich, approachable cup is nicely rounded out by its juicy mango acidity.',
                    'varietal' => 'Tabi indo',
                    'altitude' => '1630-1680m',
                    'sku' => strtolower(str_replace(" ", "-", 'Finca Julia')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Honey, Purple Grape, Mango, Chocolate',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '11',
                    'brand_type_id' => '1',
                    'characteristic_id' => '1',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 8,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Finca Julia')) . ' - 250g',
                            'price' => '75',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'La Chiquita',
                    'description' => 'Smooth, fruity and sweet, with notes of vanilla, lavender and meyer lemon. This anaerobic naturally processed coffee may change your whole perception of what coffee can be.',
                    'varietal' => 'Tabi',
                    'altitude' => '1500m',
                    'sku' => strtolower(str_replace(" ", "-", 'La Chiquita')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Mandarin, Juicy, Lemon Candy, Black Tea, Lavender',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '2',
                    'brand_type_id' => '1',
                    'characteristic_id' => '3',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 8,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '3',
                            'reward_point' => '1',
                            'title' => '130g',
                            'sku' => strtolower(str_replace(" ", "-", 'La Chiquita')) . ' - 130g',
                            'price' => '115',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Panama Geisha Echo',
                    'description' => 'This process version of this coffee is super juicy, combining the complexity and florality of the iconic Panamanian gesha with the kicked up fruity sweetness we expect from carbonic maceration processing. We taste creamy caramel, mandarin orange, a whole field of flowers, and much more.',
                    'varietal' => 'Geisha',
                    'altitude' => 'Above 1900MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Panama Geisha Echo')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Mandarin, Caramel, Nectarine, White Wine',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '11',
                    'brand_id' => '11',
                    'brand_type_id' => '1',
                    'characteristic_id' => '8',
                    'best_for_id' => '1',
                    'level_id' => '5',
                    'process_id' => 12,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Panama Geisha Echo')) . ' - 250g',
                            'price' => '315',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Finca Hartmann',
                    'description' => 'This is one smooth & balanced coffee. With notes of berry fruit, citrus and floral it\'s a real delight.',
                    'varietal' => 'Geisha',
                    'altitude' => '1500m',
                    'sku' => strtolower(str_replace(" ", "-", 'Finca Hartmann')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Stone Fruit, Floral, Brown sugar',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '11',
                    'brand_id' => '7',
                    'brand_type_id' => '1',
                    'characteristic_id' => '8',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 2,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Finca Hartmann')) . ' - 200g',
                            'price' => '115',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Epoca COE',
                    'description' => 'Bushels of blueberry juiciness, backed up by smooth chocolaty sweetness and a hint of nutmeg.',
                    'varietal' => 'Yellow Catuai',
                    'altitude' => '900-1000m',
                    'sku' => strtolower(str_replace(" ", "-", 'Epoca COE')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Jackfruit, Black Cherry',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '1',
                    'brand_id' => '18',
                    'brand_type_id' => '1',
                    'characteristic_id' => '3',
                    'best_for_id' => '1',
                    'level_id' => '3',
                    'process_id' => 1,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Epoca COE')) . ' - 250g',
                            'price' => '95',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Geisha Limitless',
                    'description' => 'The coffee that has been consistently blowing people\'s minds and is still mindblowing, it tastes like raw honey, white plums, fresh strawberry, tangerine, and much, much more.',
                    'varietal' => 'Geisha',
                    'altitude' => 'Above 1,900MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Geisha Limitless')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Strawberry, Honey, Tangerine, White Plums',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '11',
                    'brand_id' => '11',
                    'brand_type_id' => '1',
                    'characteristic_id' => '8',
                    'best_for_id' => '1',
                    'level_id' => '5',
                    'process_id' => 14,
                    'seller_id' => '2',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Geisha Limitless')) . ' - 250g',
                            'price' => '310',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],

                // international roasters
                [
                    'product_name' => 'Bosques De San Francisco',
                    'description' => 'Long-lingering, super sweet, and chock-full of honey-roasted nuttiness, this is a great representation of the Pacamara varietal.',
                    'varietal' => 'Pacamara',
                    'altitude' => '1720m',
                    'sku' => strtolower(str_replace(" ", "-", 'Bosques De San Francisco')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Brown Sugar, Orange, Honey',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '9',
                    'brand_id' => '13',
                    'brand_type_id' => '2',
                    'characteristic_id' => 4,
                    'best_for_id' => 6,
                    'level_id' => 3,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Bosques De San Francisco')) . ' - 200g',
                            'price' => '60',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Sitio Joaninha',
                    'description' => 'Bold, juicy and peachy - an absolutely classic profile. With its deep chocolaty notes, this one\'s a great match for milk.',
                    'varietal' => 'Red Catuai',
                    'altitude' => '1240m',
                    'sku' => strtolower(str_replace(" ", "-", 'Sitio Joaninha')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'White Grapes, Milk Chocolate & Peach',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '1',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 1,
                    'best_for_id' => 2,
                    'level_id' => 3,
                    'process_id' => 1,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Sitio Joaninha')) . ' - 1kg',
                            'price' => '206',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Dos Quebradas',
                    'description' => 'Interested in fruity coffees, but don\'t know where to start? Here\'s your gateway: gentle pear sweetness and a soft lemon acidity make this cup equal parts approachable and exciting.',
                    'varietal' => 'Castillo & Colombia',
                    'altitude' => '1800 MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Dos Quebradas')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Lemonade, Pear & Marmalade',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 1,
                    'level_id' => 5,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Dos Quebradas')) . ' - 250g',
                            'price' => '79',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Sítio Canaã',
                    'description' => 'Right down the middle (but nothing mediocre about it), this coffee is about as balanced as it gets. Sweet, nutty and utterly sippable.',
                    'varietal' => 'Red Catuai',
                    'altitude' => '1200-1350MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Sitio Canaa')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Walnut, Pear & Dates',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '1',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 4,
                    'best_for_id' => 1,
                    'level_id' => 5,
                    'process_id' => 11,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Sitio Canaa')) . ' - 250g',
                            'price' => '90',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Decaf',
                    'description' => 'Decaffeination processed for maximum sweetness, hold the calories. We\'re loving this as our afternoon cup - sweet and nutty, it reminds us of grape, apple and hazelenut.',
                    'varietal' => 'Castillo Columbia',
                    'altitude' => '1000-1100MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Decaf')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Apple, Hazelnut, & White Grape',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 1,
                    'best_for_id' => 10,
                    'level_id' => 5,
                    'process_id' => 13,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Decaf')) . ' - 1kg',
                            'price' => '205',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Consacá',
                    'description' => 'Apple, tangerine, and Raisin - an unlikely combo, but these notes come together beautifully in this surprisingly elegant cup.',
                    'varietal' => 'Colombia, Castillo, Caturra',
                    'altitude' => '1900-2000m',
                    'sku' => strtolower(str_replace(" ", "-", 'Consaca')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Green Apple, Tangerine, Rum & Raisin',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 3,
                    'best_for_id' => 2,
                    'level_id' => 3,
                    'process_id' => 14,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1Kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Consaca')) . ' - 1Kg',
                            'price' => '206',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Robles Pacamara',
                    'description' => 'Interested in fruity coffees, but don\'t know where to start? Here\'s your gateway: gentle mango sweetness and a soft lemon acidity make this cup equal parts approachable and exciting.',
                    'varietal' => 'Pacamara',
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Robles Pacamara')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Lemonade, Tropical Fruit, Cardamom',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '10',
                    'brand_id' => '13',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 10,
                    'level_id' => 4,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Robles Pacamara')) . ' - 200g',
                            'price' => '74',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Sul de Minas',
                    'description' => 'Hazelnut sweetness wraps up notes of almond and orange like a comfy sweater. If you\'re looking for a cup of comfort, invite this one in.',
                    'varietal' => 'Catuai',
                    'altitude' => '800-1100m',
                    'sku' => strtolower(str_replace(" ", "-", 'Sul de Minas')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Citrus, Almond, Hazelnut',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '1',
                    'brand_id' => '15',
                    'brand_type_id' => '2',
                    'characteristic_id' => 1,
                    'best_for_id' => 2,
                    'level_id' => 3,
                    'process_id' => 1,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Sul de Minas')) . ' - 250g',
                            'price' => '59',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Competition Blend',
                    'description' => 'For lovers of intense dark roast flavors, this French Roast dials it up to onze with a huge body to match.',
                    'varietal' => null,
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Competition Blend')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Pine, Chocolate, Cinamon',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '4',
                    'brand_id' => '16',
                    'brand_type_id' => '2',
                    'characteristic_id' => 9,
                    'best_for_id' => 2,
                    'level_id' => 6,
                    'process_id' => null,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Competition Blend')) . ' - 250g',
                            'price' => '48',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Los Cambulos',
                    'description' => 'This lactic - anaerobic coffee is super complex with rich tropical notes of Papaya, Blueberry Compote, Coconut and Banoffee. This coffee is rich with sweet dessert like notes.',
                    'varietal' => 'Castillo',
                    'altitude' => '1600m',
                    'sku' => strtolower(str_replace(" ", "-", 'Los Cambulos')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Papaya, Coconut',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '2',
                    'brand_id' => '17',
                    'brand_type_id' => '2',
                    'characteristic_id' => 5,
                    'best_for_id' => 3,
                    'level_id' => 3,
                    'process_id' => 8,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Los Cambulos')) . ' - 200g',
                            'price' => '110',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Duromina Organic',
                    'description' => 'This terrifically balanced coffee with jasmin notes, vanilla sweetness and apricot acidity is even more impressive when you learn that it\'s the first crop from Duromina\'s farm.',
                    'varietal' => 'Ethiopian Heirloom',
                    'altitude' => '2000MASL',
                    'sku' => strtolower(str_replace(" ", "-", 'Duromina Organic')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Jasmin, Apricot & Madagascar Vanilla',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '4',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 4,
                    'best_for_id' => 1,
                    'level_id' => 5,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Duromina Organic')) . ' - 250g',
                            'price' => '92',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Nyeri',
                    'description' => 'Silky, sweet, and slightly savory in the best way. This Kenyan cup is full to the brim with citrusy notes that keep each sip interesting. This is a punchy cup, packed with sweet lime and jammy notes',
                    'varietal' => 'SL28',
                    'altitude' => '1600-2000m',
                    'sku' => strtolower(str_replace(" ", "-", 'Nyeri')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Black Currant ',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '6',
                    'brand_id' => '15',
                    'brand_type_id' => '2',
                    'characteristic_id' => 3,
                    'best_for_id' => 1,
                    'level_id' => 3,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Nyeri')) . ' - 250g',
                            'price' => '79',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ]
                    ]
                ],
                [
                    'product_name' => 'Huila',
                    'description' => 'Roasting dark while maintaining a distinct flavor profile takes a certain degree of wizardry. This smoky, delicious single origin knocks it out of the park.',
                    'varietal' => 'Caturra',
                    'altitude' => '1300-1900m',
                    'sku' => strtolower(str_replace(" ", "-", 'Huila')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Dark Berry',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '15',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 6,
                    'level_id' => 6,
                    'process_id' => 2,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Huila')) . ' - 250g',
                            'price' => '64',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'La Cocha',
                    'description' => 'This fruity-sweet number blew us away with its silky body and gorgeously refined notes of orange and maple.',
                    'varietal' => 'Castillo, Columbia, Typica, Maragogipe',
                    'altitude' => '1950-2050m',
                    'sku' => strtolower(str_replace(" ", "-", 'La Cocha')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Blood Orange, Lemon Zest, Maple',
                    'type_id' => null,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '2',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 3,
                    'best_for_id' => 1,
                    'level_id' => 5,
                    'process_id' => 11,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '3',
                            'reward_point' => '1',
                            'title' => '130g',
                            'sku' => strtolower(str_replace(" ", "-", 'La Cocha')) . ' - 130g',
                            'price' => '80',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Rabanales Typica',
                    'description' => 'This is one smooth & balanced coffee. With notes of passion fruit and marmalade, it\'s a real delight.',
                    'varietal' => 'Typica',
                    'altitude' => null,
                    'sku' => strtolower(str_replace(" ", "-", 'Rabanales Typica')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Passion Fruit, Marmalade',
                    'type_id' => 2,
                    'coffee_type_id' => 2,
                    'category_id' => 2,
                    'origin_id' => '9',
                    'brand_id' => '13',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 10,
                    'level_id' => 3,
                    'process_id' => 5,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '5',
                            'reward_point' => '1',
                            'title' => '200g',
                            'sku' => strtolower(str_replace(" ", "-", 'Rabanales Typica')) . ' - 200g',
                            'price' => '74',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Santa Felisa',
                    'description' => 'Get ready to be swept off your feet - gently and gracefully. Delicate floral aromatics, soft citrus acidity and a bit of ginger spice make a perfect cup for a summer afternoon.',
                    'varietal' => 'Geisha',
                    'altitude' => '1500-1900m',
                    'sku' => strtolower(str_replace(" ", "-", 'Santa Felisa')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Peach, Wildflower, White Tea',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '9',
                    'brand_id' => '19',
                    'brand_type_id' => '2',
                    'characteristic_id' => 6,
                    'best_for_id' => 1,
                    'level_id' => 3,
                    'process_id' => 4,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '6',
                            'reward_point' => '1',
                            'title' => '225g',
                            'sku' => strtolower(str_replace(" ", "-", 'Santa Felisa')) . ' - 225g',
                            'price' => '124',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Kamwangi AB',
                    'description' => 'This wildly rich natural process coffee comes from the Kamwangi mill, pioneers of coffee processing in Kenya. Its wild strawberry, vanilla and white grape sweetness is complemented by an intense rosey acidity for a very complex cup.',
                    'varietal' => 'SL 34',
                    'altitude' => '1800-1900m',
                    'sku' => strtolower(str_replace(" ", "-", 'Kamwangi AB')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Strawberry, White Grape, Vanilla & Rose',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '6',
                    'brand_id' => '14',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 1,
                    'level_id' => 5,
                    'process_id' => 11,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Kamwangi AB')) . ' - 250g',
                            'price' => '85',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '10',
                            'reward_point' => '1',
                            'title' => '1kg',
                            'sku' => strtolower(str_replace(" ", "-", 'Kamwangi AB')) . ' - 1kg',
                            'price' => '85',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
                [
                    'product_name' => 'Manga Larga Series',
                    'description' => 'Right down the middle (but nothing mediocre about it), this coffee is about as balanced as it gets. Sweet, nutty and utterly sippable.',
                    'varietal' => 'Yellow Buorbon',
                    'altitude' => '970m',
                    'sku' => strtolower(str_replace(" ", "-", 'Manga Larga Series')),
                    'price' => '100',
                    'quantity' => '200',
                    'flavor_note' => 'Hazelnut, Dried Plum, Cacao Nibs',
                    'type_id' => 1,
                    'coffee_type_id' => 1,
                    'category_id' => 3,
                    'origin_id' => '1',
                    'brand_id' => '20',
                    'brand_type_id' => '2',
                    'characteristic_id' => 8,
                    'best_for_id' => 3,
                    'level_id' => 3,
                    'process_id' => 8,
                    'seller_id' => '1',
                    'tax_class_id' => '1',
                    'grind_type' => 1,
                    'status' => 1,
                    'variants' => [
                        [
                            'weight_id' => '7',
                            'reward_point' => '1',
                            'title' => '250g',
                            'sku' => strtolower(str_replace(" ", "-", 'Manga Larga Series')) . ' - 250g',
                            'price' => '130',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                        [
                            'weight_id' => '8',
                            'reward_point' => '1',
                            'title' => '500g',
                            'sku' => strtolower(str_replace(" ", "-", 'Manga Larga Series')) . ' - 500g',
                            'price' => '260',
                            'quantity' => '100',
                            'grind_ids' => '1,2,3,4,5,6,7,8',
                            'is_default' => 1,
                            'status' => '1',
                        ],
                    ]
                ],
            ];

            foreach ($products as $key => $product) {
                $variants = $product['variants'] ?? [];
                unset($product['variants']);
                $product['display_order'] = ($key + 1);
                $save = Product::create($product);
                if ($save) {
                    $image_id = $product['brand_type_id'] > 1 ? ($save->id - 26) : $save->id;
                    Image::create([
                        'type' => 'product',
                        'content_id' => $save->id,
                        'image_path' => 'uploads/products/' . $product['brand_type_id'] . '/' . $image_id . '.png',
                        'status' => 1
                    ]);

                    foreach ($variants as $variant) {
                        $variant['product_id'] = $save->id;
                        Variant::create($variant);
                    }
                }
            }
        }
    }
}
